name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310}
          - {name: Typing, python: '3.9', os: ubuntu-latest, tox: typing}
          - {name: Style, python: '3.9', os: ubuntu-latest, tox: style}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - name: cache mypy
        uses: actions/cache@v3.0.3
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('setup.cfg') }}
        if: matrix.tox == 'typing'
      - run: pip install tox
      - run: tox -e ${{ matrix.tox }}
